# Spring Boot configuration

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    instance:
      preferIpAddress: true


spring:
  application:
    name: Employee-Application
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/xyzCompany      #postgres
    username: postgres
    password: 1234          #secret
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  cloud:
      compatibility-verifier:
        enabled: false

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: SpringBootKeycloak
  resource: login-app
  public-client: true
  bearer-only: true



